### ISSUE TITLE
Card not rendering correctly inside sidebar view mode

### ISSUE THREAD

**Issue by nickh66** [SNoof85/lovelace-tempometer-gauge-card-deprecated#57]
**Describe the bug**
I have added a 2 column grid card to a sidebar view in a dashboard & added 4 x this card to the grid.  In this sidebar view the graph rendering seems to not resize correctly for this narrower space.

**Version of the card**
You will find this information in console of your browser.
Version : 1.4

**Screenshots**
![image](https://user-images.githubusercontent.com/11672847/162546551-59995005-6290-4a6d-9d7f-038b4389e644.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome & edge tested]
 - Version [100.0.4896.75 (Official Build) (64-bit)]

**Additional context**
Seems to not be a problem if this card combo is used in a main view.
This is the code that i am using for what you see in the screen shot.

`square: false
columns: 2
type: grid
cards:
  - type: custom:tempometer-gauge-card
    entity: sensor.outside_temperature_average
    min: 0
    max: 50
    title: Outside Temp
    card_style: custom
    icon1: mdi:flash-off
    icon2: mdi:flash-outline
    icon3: mdi:flash
    severity:
      green: 10
      yellow: 25
      red: 35
      max: 50
  - type: custom:tempometer-gauge-card
    entity: sensor.outside_humidity_average
    min: 0
    max: 100
    title: Outside Humidity
    card_style: custom
    icon1: mdi:flash-off
    icon2: mdi:flash-outline
    icon3: mdi:flash
    severity:
      green: 50
      yellow: 60
      red: 70
      max: 80
  - type: custom:tempometer-gauge-card
    entity: sensor.house_temperature_average
    min: 0
    max: 50
    title: Inside Temp
    card_style: custom
    icon1: mdi:flash-off
    icon2: mdi:flash-outline
    icon3: mdi:flash
    severity:
      green: 10
      yellow: 25
      red: 35
      max: 50
  - type: custom:tempometer-gauge-card
    entity: sensor.house_humidity_average
    min: 0
    max: 100
    title: Inside Humidity
    card_style: custom
    icon1: mdi:flash-off
    icon2: mdi:flash-outline
    icon3: mdi:flash
    severity:
      green: 50
      yellow: 60
      red: 70
      max: 80
view_layout:
  position: sidebar
`

**Comment by nickh66** [comment]
Looks like the rendering is also a bit off in other scenarios too.  Seems like the resizing of the gauge is not handling narrow screen realestate.  I included a couple of other examples below.

![image](https://user-images.githubusercontent.com/11672847/162552917-afc04448-4c94-4eca-bc36-173e735166a3.png)

![image](https://user-images.githubusercontent.com/11672847/162553335-0c2bbd6c-fdb2-4bc2-b863-b64732d77cd0.png)

**Comment by iaah05** [comment]
I get this too and I think the issue was previously submitted but the author said he would not fix. Maybe someone can fork?
